spring:
  ai:
    mcp:
      server:
        name: "Calisync MCP Server"
        version: "1.0.0"
        protocol: SSE
        sse-endpoint: "/calimcp/sse"
        sse-message-endpoint: "/calimcp/message"


logging.level:
  org.springframework.ai.mcp: ERROR
  org.springframework.support.PostProcessorRegistrationDelegate$BeanPostProcessorCheckor: ERROR
  io.modelcontextprotocol.server: ERROR

server:
  forward-headers-strategy: native